# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wca.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\twca.proto\x12\x03wca\"\x95\x01\n\x0eToServerExtras\x12\x0c\n\x04step\x18\x01 \x01(\t\x12\x31\n\nclient_cmd\x18\x02 \x01(\x0e\x32\x1d.wca.ToServerExtras.ClientCmd\"B\n\tClientCmd\x12\n\n\x06NO_CMD\x10\x00\x12\x0e\n\nZOOM_START\x10\x01\x12\r\n\tZOOM_STOP\x10\x02\x12\n\n\x06REPORT\x10\x03\"\xa1\x02\n\x0eToClientExtras\x12\x0c\n\x04step\x18\x01 \x01(\t\x12 \n\tzoom_info\x18\x02 \x01(\x0b\x32\r.wca.ZoomInfo\x12\x33\n\x0bzoom_result\x18\x03 \x01(\x0e\x32\x1e.wca.ToClientExtras.ZoomResult\x12\x31\n\nuser_ready\x18\x04 \x01(\x0e\x32\x1d.wca.ToClientExtras.UserReady\":\n\nZoomResult\x12\x0b\n\x07NO_CALL\x10\x00\x12\x0e\n\nCALL_START\x10\x01\x12\x0f\n\x0b\x45XPERT_BUSY\x10\x02\";\n\tUserReady\x12\r\n\tNO_CHANGE\x10\x00\x12\x07\n\x03SET\x10\x01\x12\t\n\x05\x43LEAR\x10\x02\x12\x0b\n\x07\x44ISABLE\x10\x03\"O\n\x08ZoomInfo\x12\x11\n\tjwt_token\x18\x01 \x01(\t\x12\x16\n\x0emeeting_number\x18\x02 \x01(\t\x12\x18\n\x10meeting_password\x18\x03 \x01(\tB\x18\n\x0e\x65\x64u.cmu.cs.wcaB\x06Protosb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wca_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016edu.cmu.cs.wcaB\006Protos'
  _TOSERVEREXTRAS._serialized_start=19
  _TOSERVEREXTRAS._serialized_end=168
  _TOSERVEREXTRAS_CLIENTCMD._serialized_start=102
  _TOSERVEREXTRAS_CLIENTCMD._serialized_end=168
  _TOCLIENTEXTRAS._serialized_start=171
  _TOCLIENTEXTRAS._serialized_end=460
  _TOCLIENTEXTRAS_ZOOMRESULT._serialized_start=341
  _TOCLIENTEXTRAS_ZOOMRESULT._serialized_end=399
  _TOCLIENTEXTRAS_USERREADY._serialized_start=401
  _TOCLIENTEXTRAS_USERREADY._serialized_end=460
  _ZOOMINFO._serialized_start=462
  _ZOOMINFO._serialized_end=541
# @@protoc_insertion_point(module_scope)
